# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
