# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0003_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='plublished',
            field=models.BooleanField(default=False),
        ),
    ]
