# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0004_board_plublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='layers',
            field=models.TextField(blank=True),
        ),
    ]
