# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0006_board_base64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='plublished',
            new_name='published',
        ),
    ]
